### ISSUE TITLE
Storm Issues with Chessboard

### ISSUE THREAD

**Issue by creijon** [usd-wg/assets#30]
Linking to the issues that appear to be in Storm with the Chessboard.  This could be due to the authoring of the asset itself, could someone check?

https://github.com/PixarAnimationStudios/USD/issues/2255

**Comment by jcowles** [comment]
cc @pablode 

The screenshots in Storm look like the normals are potentially inverted, in addition to the other issues

**Comment by pablode** [comment]
Hey, unfortunately I don't have time right now to debug this further, but I believe that the normal map may be interpreted as sRGB because image colorspaces are not translated from Hydra to MaterialX. There are two open issues:
https://github.com/PixarAnimationStudios/USD/issues/1523
https://github.com/PixarAnimationStudios/USD/issues/1878

Afaik it should render fine in Karma because there only \<image\>s of type color3 are sRGB-decoded, and \<image\>s of type vector3 (which are used for normal maps) are not.

**Comment by jonny-apple** [comment]
Thanks for looking into the @pablode , I'll link those issues over to the one I created in USD.

**Comment by jcowles** [comment]
Looks like both of the issues cited above are now closed - should we revisit this with a recent build of USD?

**Comment by creijon** [comment]
Yes, I can confirm it is now resolved.  Closing.
