### ISSUE TITLE
usdchecker doesn't recognize .mtlx file references

### ISSUE THREAD

**Issue by crydalch** [usd-wg/assets#82]
When usdchecker runs on a StandardShaderBall commit, it fails to recognize the .mtlx files.

Maybe the USD we're using just needs to be updated to the latest, which includes UsdMaterialX by default?

**Comment by pablode** [comment]
The GH script installs the latest usd-core PyPI package, which is 23.11. However, it seems like usd-core has been built without MaterialX support enabled :(
https://github.com/PixarAnimationStudios/OpenUSD/blob/3bcae24e7d62b732b9cb2ac47cdcaab41bf9ca7f/azure-pypi-pipeline.yml#L90

Additionally, this PR would be needed to make usdchecker happy: https://github.com/PixarAnimationStudios/OpenUSD/pull/2966

I guess one workaround could be, since the actual Python script resides in this repo, to ignore/demote error messages of a certain type according to a RegEx: https://github.com/usd-wg/assets/blob/746b850badda03fdc1961dd82fda50b114c90538/.github/usdchecker.py#L122C5-L140

**Comment by crydalch** [comment]
Argh :( That's unfortunate, thanks for figuring that out.

@jcowles what do you think about the suggestion by @pablode, to modify our usdchecker script to ignore missing references that refer to .mtlx documents? Or if we have a PR where that's the only failure (like #80), do we just merge it anyway? With the hope that usd-core will eventually end up with mtlx included?

**Comment by crydalch** [comment]
Closing as the PR was merged.
